### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by matt-forster** [frogamic/abouttime#1]
Hey @frogamic, 

I emailed you earlier about the possibilities of color on this watch face, and I figured I'd search it up on Github just to see if it was around - here you are!

If you need any help, I'd be happy to lend a hand!

**Comment by frogamic** [comment]
Hey @forstermatth,
I might need some help with the html/javascript for the config page.
I've created a branch `configurable` and I'm working on adding the configuration options.
I'll keep in touch.
